"""
Structured logging schemas for MORPH-DA experiments.

All experiment runs are logged as JSONL files.
Each schema maps to one record type.
"""

from __future__ import annotations

import hashlib
import json
import os
import platform
import sys
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


@dataclass
class RunManifest:
    """Written once per experiment run. Tracks full reproducibility metadata."""
    run_id: str
    experiment_name: str
    timestamp_utc: str
    git_commit: str
    python_version: str
    platform: str
    task_split_hash: str
    relation_library_version: str
    random_seeds: list[int]
    model_ids: dict[str, str]
    notes: str = ""

    @classmethod
    def create(
        cls,
        experiment_name: str,
        task_specs: list,
        seeds: list[int],
        model_ids: dict[str, str],
        notes: str = "",
    ) -> "RunManifest":
        import subprocess
        try:
            git_commit = subprocess.check_output(
                ["git", "rev-parse", "--short", "HEAD"],
                stderr=subprocess.DEVNULL,
            ).decode().strip()
        except Exception:
            git_commit = "unknown"

        task_hash = hashlib.sha256(
            json.dumps([t.task_id for t in task_specs], sort_keys=True).encode()
        ).hexdigest()[:12]

        return cls(
            run_id=datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S"),
            experiment_name=experiment_name,
            timestamp_utc=datetime.now(timezone.utc).isoformat(),
            git_commit=git_commit,
            python_version=sys.version,
            platform=platform.platform(),
            task_split_hash=task_hash,
            relation_library_version="0.1.0",
            random_seeds=seeds,
            model_ids=model_ids,
            notes=notes,
        )


@dataclass
class ProgramRecord:
    """One candidate program generated by an agent (natural track)."""
    program_id: str
    task_id: str
    scenario_id: str
    data_seed: int
    source: str        # "natural" | "rulemut" | "llmmut" | "reference"
    model_id: str
    agent_harness: str
    generated_program: str
    execution_success: bool
    source_output: Any
    gold_correct: bool | None   # None when gold is unknown
    input_tokens: int = 0
    output_tokens: int = 0
    model_latency_ms: float = 0.0
    python_latency_ms: float = 0.0


@dataclass
class MutantRecord:
    """One candidate mutant produced by the mutation engine."""
    mutant_id: str
    task_id: str
    reference_hash: str
    generation_source: str    # "rulemut" | "llmmut"
    mutation_family: str
    mutation_operator: str
    mutated_program: str
    syntax_valid: bool
    execution_valid: bool
    contract_valid: bool
    non_equivalent_seeds: list[int]
    held_out_operator: bool
    manual_audit: dict | None = None


@dataclass
class RelationExecutionRecord:
    """One relation check on one program × one transformed case."""
    program_id: str
    task_id: str
    relation_id: str
    relation_family: str
    transformation_seed: int
    source_output: Any
    follow_up_output: Any
    expected_relation: str
    passed: bool
    violation_magnitude: float | None
    python_latency_ms: float
    witness: dict | None = None


@dataclass
class VerificationRecord:
    """Aggregated verification result for one program."""
    program_id: str
    task_id: str
    data_seed: int
    source: str
    decision: str           # "pass" | "fail" | "error"
    applicable_relations: int
    violated_relations: int
    total_python_runs: int
    total_latency_ms: float
    witnesses: list[dict] = field(default_factory=list)


@dataclass
class RepairRecord:
    """One repair attempt."""
    program_id: str
    task_id: str
    repair_method: str      # R0-R8 from paper Table 14.2
    trigger: str
    feedback_type: str
    repaired_program: str | None
    execution_success: bool
    repaired_output: Any
    gold_correct: bool | None
    model_latency_ms: float
    input_tokens: int
    output_tokens: int


def record_to_dict(record: Any) -> dict:
    """Convert a dataclass record to a JSON-serializable dict."""
    d = asdict(record) if hasattr(record, "__dataclass_fields__") else vars(record)
    # Coerce non-serializable types
    def _fix(v: Any) -> Any:
        if hasattr(v, "item"):  # numpy scalar
            return v.item()
        if hasattr(v, "tolist"):  # numpy array
            return v.tolist()
        return v
    return {k: _fix(v) for k, v in d.items()}
